# Generated by Django 4.0.4 on 2022-05-11 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comida',
            fields=[
                ('idComida', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Producto')),
                ('tipoProducto', models.CharField(max_length=20, verbose_name='Tipo de Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_prod', models.IntegerField(max_length=5, primary_key=True, serialize=False, verbose_name='id producto')),
                ('nombre', models.CharField(max_length=25, verbose_name='Nombre Produtcto')),
                ('desc', models.CharField(max_length=144, verbose_name='Descripcion')),
                ('precio', models.IntegerField(max_length=6, verbose_name='precio')),
                ('img', models.CharField(max_length=50, verbose_name='Ruta a imagen')),
            ],
        ),
    ]
