# Generated by Django 4.0.4 on 2022-05-11 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='cod_prod',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='id producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='img',
            field=models.ImageField(upload_to='img/', verbose_name='Ruta a imagen'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(verbose_name='precio'),
        ),
    ]
